package com.mina.yuedu.ui;
import android.app.*;import android.content.*;import android.os.*;import com.mina.yuedu.core.*;import com.mina.yuedu.model.*;import com.mina.yuedu.network.*;import java.text.SimpleDateFormat;import java.util.*;
public final class DedupeController implements DedupeView.Listener {
 public interface Host {void chooseFiles();void importReader(String json);void saveJson(String name,String json);}
 private enum State{IDLE,RUNNING,CANCELLING,PARTIAL_RESULT,COMPLETED,FAILED}
 private final Activity activity;private final DedupeView view;private final Host host;private final Handler main=new Handler(Looper.getMainLooper());private FetchManager manager;private final SourceBuckets buckets=new SourceBuckets();private final List<InvalidSource> extraInvalid=new ArrayList<>();private DedupeResult result;private DedupeMode mode=DedupeMode.STANDARD;private final OperationMode operationMode=new OperationMode(DedupeMode.STANDARD);private boolean clean,partial,discard;private int concurrency=4,nextOrder,localFileCount;private State state=State.IDLE;
 public DedupeController(Activity a,DedupeView v,Host h){activity=a;view=v;host=h;view.setListener(this);}
 public void addLocalJson(String name,String json){operationMode.start();mode=operationMode.resultMode();SourceParser.ParseResult p=SourceParser.parseArray(json,nextOrder);synchronized(buckets){buckets.addLocal(p.getRecords());}extraInvalid.addAll(p.getInvalid());nextOrder+=p.getRecords().size()+p.getInvalid().size();if(!p.getRecords().isEmpty()){localFileCount++;view.showLocalStatus(localFileCount,buckets.localCount());}recompute(false);}
 @Override public void onChooseFiles(){host.chooseFiles();}
 @Override public void onStart(List<String> urls,DedupeMode m,int c,boolean cl){if(state==State.RUNNING)return;operationMode.select(m);operationMode.start();mode=operationMode.resultMode();concurrency=c;clean=cl;partial=false;discard=false;synchronized(buckets){buckets.replaceNetwork(Collections.<SourceRecord>emptyList());}extraInvalid.clear();if(!ParseRequestDecision.shouldRun(buckets.localCount(),urls.size())){view.showError("请选择本地文件或输入网络地址");return;}if(urls.isEmpty()){recompute(false);return;}startFetch(urls,false);}
 private void startFetch(List<String> urls,boolean followUp){state=State.RUNNING;manager=new FetchManager();manager.start(urls,concurrency,new FetchListener(){public void onProgress(FetchProgress p){main.post(()->view.showRunning(p));}public void onItem(String url,String body){SourceParser.ParseResult p=SourceParser.parseArray(body,nextOrder);synchronized(buckets){if(!p.getRecords().isEmpty()){buckets.addNetwork(p.getRecords());nextOrder+=p.getRecords().size();}else{List<String> found=SourceParser.discoverYckJsonUrls(body,url);if(found.isEmpty())extraInvalid.addAll(p.getInvalid());else synchronized(discovered){discovered.addAll(found);}}}}public void onFailure(String u,String m){synchronized(extraInvalid){extraInvalid.add(new InvalidSource(InvalidSource.Kind.NETWORK_FAILURE,u+" · "+m));}}public void onFinished(boolean cancelled,boolean keep){main.post(()->{if(discard){discard=false;state=State.IDLE;view.showCleared();return;}List<String> more; synchronized(discovered){more=new ArrayList<>(new LinkedHashSet<>(discovered));discovered.clear();}if(!cancelled&&!followUp&&!more.isEmpty()){startFetch(more,true);return;}partial=cancelled&&keep;recompute(partial);});}});}
 private final List<String> discovered=new ArrayList<>();
 @Override public void onClearAll(){if(state==State.RUNNING&&manager!=null){discard=true;manager.cancel(false);}synchronized(buckets){buckets.clearAll();}synchronized(extraInvalid){extraInvalid.clear();}synchronized(discovered){discovered.clear();}localFileCount=0;nextOrder=0;result=null;state=State.IDLE;view.setInputText("");view.showLocalStatus(0,0);view.showCleared();}
 @Override public void onStop(){if(state!=State.RUNNING)return;new AlertDialog.Builder(activity).setTitle("停止解析？").setItems(new String[]{"处理已加载数据","全部放弃","继续解析"},(d,w)->{if(w==0){state=State.CANCELLING;partial=true;manager.cancel(true);}else if(w==1){state=State.CANCELLING;discard=true;manager.cancel(false);}}).show();}
 @Override public void onModeChanged(DedupeMode m,boolean cl){operationMode.select(m);clean=cl;}
 private void recompute(boolean isPartial){List<SourceRecord> copy; synchronized(buckets){copy=buckets.all();}DedupeResult base=DedupeEngine.run(copy,mode,clean);List<InvalidSource> all=new ArrayList<>(base.getInvalid());synchronized(extraInvalid){all.addAll(extraInvalid);}result=new DedupeResult(copy.size(),base.getRetained(),base.getDuplicateGroups(),all);state=isPartial?State.PARTIAL_RESULT:State.COMPLETED;view.showResult(result,isPartial,mode,buckets.localCount(),buckets.networkCount());}
 public String exportJson(){if(result==null)return null;List<Object> a=new ArrayList<>();String stamp=new SimpleDateFormat("yyyy-M-d",Locale.CHINA).format(new Date());String mark="✔"+stamp+"检验去重（优质"+result.getRetained().size()+"）";for(SourceRecord s:result.getRetained()){Map<String,Object> m=new LinkedHashMap<>(s.getRaw());m.put("bookSourceName",s.getName());Object g=m.get("bookSourceGroup");String gs=g==null?"":String.valueOf(g);if(!gs.contains(mark))m.put("bookSourceGroup",gs.isEmpty()?mark:gs+","+mark);a.add(m);}return MiniJson.stringify(a);}
 @Override public void onImport(){String j=exportJson();if(j==null)view.showError("没有可导入的数据");else host.importReader(j);}@Override public void onSave(){String j=exportJson();if(j==null){view.showError("没有可保存的数据");return;}String d=new SimpleDateFormat("yyyy-MM-dd",Locale.CHINA).format(new Date());host.saveJson("去重_"+result.getRetained().size()+"_"+d+".json",j);}
 public void restoreOptions(DedupeMode m,int c,boolean cl){mode=m==null?DedupeMode.STANDARD:m;operationMode.select(mode);concurrency=Math.max(1,Math.min(5,c));clean=cl;}
 public DedupeMode getMode(){return operationMode.selectedMode();}public int getConcurrency(){return concurrency;}public boolean isCleanNames(){return clean;}
}
