package com.mina.yuedu.network;
import com.mina.yuedu.core.MiniJson;import com.mina.yuedu.model.*;import java.net.*;import java.util.*;import java.util.regex.*;
public final class SourceParser {
 public static final class ParseResult {private final List<SourceRecord> records;private final List<InvalidSource> invalid;ParseResult(List<SourceRecord>r,List<InvalidSource>i){records=r;invalid=i;}public List<SourceRecord>getRecords(){return records;}public List<InvalidSource>getInvalid(){return invalid;}}
 private SourceParser(){}
 public static ParseResult parseArray(String json,int start){List<SourceRecord> out=new ArrayList<>();List<InvalidSource> bad=new ArrayList<>();Object root;try{root=MiniJson.parse(json);}catch(Exception e){bad.add(new InvalidSource(InvalidSource.Kind.NOT_JSON_ARRAY,e.getMessage()));return new ParseResult(out,bad);}if(!(root instanceof List)){bad.add(new InvalidSource(InvalidSource.Kind.NOT_JSON_ARRAY,"root is not array"));return new ParseResult(out,bad);}int i=0;for(Object x:(List<?>)root){if(!(x instanceof Map)){bad.add(new InvalidSource(InvalidSource.Kind.NOT_OBJECT,"index "+i));i++;continue;}Map<String,Object> m=new LinkedHashMap<>((Map<String,Object>)x);Object n=m.get("bookSourceName"),u=m.get("bookSourceUrl");out.add(new SourceRecord(start+i,n==null?"":String.valueOf(n),u==null?null:String.valueOf(u),m));i++;}return new ParseResult(out,bad);}
 public static String extractIndirectUrl(Map<String,Object> m){for(String k:new String[]{"msg","downloadUrl","url"}){Object v=m.get(k);if(v!=null&&String.valueOf(v).matches("https?://.+"))return String.valueOf(v);}return null;}
 public static List<String> discoverYckJsonUrls(String html,String base){LinkedHashSet<String> set=new LinkedHashSet<>();Pattern p=Pattern.compile("(?:href|value|data-url)\\s*=\\s*['\"]([^'\"]+?\\.json(?:\\?[^'\"]*)?)['\"]",Pattern.CASE_INSENSITIVE);Matcher m=p.matcher(html.replace("&amp;","&"));while(m.find())add(set,m.group(1),base);Pattern raw=Pattern.compile("https?://[^\\s'\"<>]+/yuedu/(?:shuyuan|shuyuans|rss|rsss)/json/[^\\s'\"<>]+",Pattern.CASE_INSENSITIVE);m=raw.matcher(html);while(m.find())add(set,m.group(),base);return new ArrayList<>(set);}
 private static void add(Set<String>s,String raw,String base){try{URL u=new URL(new URL(base),raw);String p=u.getPath();if(p.matches("(?i).*/yuedu/(shuyuan|shuyuans|rss|rsss)/json/.*\\.json"))s.add(u.toString());}catch(Exception ignored){}}
}
