package com.mina.yuedu.core;
import java.util.*;
public final class MiniJson {
 private final String s;private int p;private MiniJson(String s){this.s=s;}
 public static Object parse(String s){MiniJson j=new MiniJson(s);Object v=j.value();j.ws();if(j.p!=s.length())throw new IllegalArgumentException("trailing JSON");return v;}
 private Object value(){ws();if(p>=s.length())throw new IllegalArgumentException("unexpected end");char c=s.charAt(p);if(c=='{')return object();if(c=='[')return array();if(c=='"')return string();if(c=='t'&&take("true"))return true;if(c=='f'&&take("false"))return false;if(c=='n'&&take("null"))return null;return number();}
 private Map<String,Object> object(){p++;Map<String,Object> m=new LinkedHashMap<>();ws();if(ch('}'))return m;do{ws();String k=string();ws();need(':');m.put(k,value());ws();}while(ch(','));need('}');return m;}
 private List<Object> array(){p++;List<Object> a=new ArrayList<>();ws();if(ch(']'))return a;do{a.add(value());ws();}while(ch(','));need(']');return a;}
 private String string(){need('"');StringBuilder b=new StringBuilder();while(p<s.length()){char c=s.charAt(p++);if(c=='"')return b.toString();if(c=='\\'){if(p>=s.length())throw new IllegalArgumentException("escape");char e=s.charAt(p++);if(e=='u'){int cp=Integer.parseInt(s.substring(p,p+4),16);p+=4;b.append((char)cp);}else{String x="\"\\/bfnrt";String y="\"\\/\b\f\n\r\t";int i=x.indexOf(e);if(i<0)throw new IllegalArgumentException("escape "+Integer.toHexString(e)+" at "+(p-1));b.append(y.charAt(i));}}else b.append(c);}throw new IllegalArgumentException("string");}
 private Number number(){int b=p;while(p<s.length()&&"-+0123456789.eE".indexOf(s.charAt(p))>=0)p++;String n=s.substring(b,p);return n.indexOf('.')>=0||n.indexOf('e')>=0||n.indexOf('E')>=0?Double.valueOf(n):Long.valueOf(n);}
 private boolean take(String x){if(s.startsWith(x,p)){p+=x.length();return true;}return false;}private void ws(){while(p<s.length()&&Character.isWhitespace(s.charAt(p)))p++;}private boolean ch(char c){if(p<s.length()&&s.charAt(p)==c){p++;return true;}return false;}private void need(char c){if(!ch(c))throw new IllegalArgumentException("expected "+c+" at "+p);}
 public static String stringify(Object v){if(v==null)return"null";if(v instanceof String)return quote((String)v);if(v instanceof Number||v instanceof Boolean)return String.valueOf(v);if(v instanceof Map){StringBuilder b=new StringBuilder("{");boolean f=true;for(Object e0:((Map<?,?>)v).entrySet()){Map.Entry<?,?> e=(Map.Entry<?,?>)e0;if(!f)b.append(',');f=false;b.append(quote(String.valueOf(e.getKey()))).append(':').append(stringify(e.getValue()));}return b.append('}').toString();}if(v instanceof Iterable){StringBuilder b=new StringBuilder("[");boolean f=true;for(Object x:(Iterable<?>)v){if(!f)b.append(',');f=false;b.append(stringify(x));}return b.append(']').toString();}return quote(String.valueOf(v));}
 private static String quote(String s){StringBuilder b=new StringBuilder("\"");for(int i=0;i<s.length();i++){char c=s.charAt(i);switch(c){case '"':b.append("\\\"");break;case '\\':b.append("\\\\");break;case '\b':b.append("\\b");break;case '\f':b.append("\\f");break;case '\n':b.append("\\n");break;case '\r':b.append("\\r");break;case '\t':b.append("\\t");break;default:if(c<0x20){String h=Integer.toHexString(c);b.append("\\u");for(int z=h.length();z<4;z++)b.append('0');b.append(h);}else b.append(c);}}return b.append('"').toString();}

}
